accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

articles/urls.py
from django.urls import path
from . import views 

app_name = 'articles'

urlpatterns = [
    path('',views.index, name='index'),

    path('create/', views.create, name='create'),
    path('<int:article_id>/comments/create/', views.comment_create, name='comment_create'),
]

auth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass
    # article_set = 
    # comment_set = 

articles/models.py
from django.db import models
from accounts.models import User
from django.conf import settings
from django.contrib.auth import get_user_model

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    # comment_set = 

    # User 모델 참조
    # 방법1. 유지보수 측면에서 어려움 (권장 X)
    # user = models.ForeignKey(User,on_delete=models.CASCADE)

    # 방법2. settings.AUTH_USER_MODEL == 'accounts.User' (권장) 
    # user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # 방법3. get_user_model() == 'User' (권장)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    # user_id = 

class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    # article_id = 

    # User 모델 참조
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    # user_id = 

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',)

class CustomAuthenticationForm(AuthenticationForm):
    pass

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    # title = forms.CharField(
    #     label='제목 입력창',
    #     widget=forms.TextInput(
    #         attrs = {'class': 'form-control'}
    #     )
    # )


    class Meta:
        model = Article
        # fields = ('title','content',)
        exclude = ('user',)
        # widgets = {
        #     'title': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control'})
        # }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.

def signup(request):
    if request.user.is_authenticated:
        return redirect('articles:index') 

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)

        if form.is_valid():

        # 회원가입시 자동 로그인 후 index로 
            user = form.save()
            auth_login(request,user)
            return redirect('articles:index')

        # 회원가입시 로그인 창으로
            # form.save()
            # return redirect('accounts:login')
    else:
        form = CustomUserCreationForm()

    context = {
        'form': form
    }

    return render(request, 'account_form.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index') 

    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)

        if form.is_valid():
            auth_login(request, form.get_user())

            # http://127.0.0.1:8000/accounts/login/?next=/articles/create/
            next_url = request.GET.get('next') # next 키를 기준으로 이동 (/articles/create/)
            
            # next 인자가 url에 있을 때 : ('/articles/create/' or 'articles:index')
            # or 단축평가 : '/articles/create/'가 True로 바로 True 값 반환

            # next 인자가 url에 없을 때 : (None or 'articles:index')
            # or 단축평가 : None이 False로 바로 뒤에 있는 값 반환 

            return redirect(next_url or 'articles:index')
    
    else:
        form = CustomAuthenticationForm()

    context = {
        'form': form
    }

    return render(request, 'account_form.html', context)

def logout(request):
    auth_logout(request)

    return redirect('accounts:login')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm, CommentForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    articles = Article.objects.all()
    comment_form = CommentForm()

    context = {
        'articles': articles,
        'comment_form': comment_form,
    }

    return render(request, 'index.html', context)


@login_required
def create(request):
    # if not request.user.is_authenticated:
    #     return redirect('accounts:login')

    if request.method == 'POST':
        form = ArticleForm(request.POST)

        if form.is_valid():
            article = form.save(commit=False)

            # article.user_id = request.user.id

            article.user = request.user 

            article.save()

            return redirect('articles:index')

    else:
        form = ArticleForm()

    context = {
        'form': form
    }

    return render(request, 'form.html', context)

@login_required
def comment_create(request, article_id):
    article = Article.objects.get(id=article_id)

    form = CommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)

        comment.user = request.user
        comment.article = article

        comment.save()

        return redirect('articles:index')

accounts/templates/account_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}

{% if request.resolver_match.url_name == 'signup' %}
    <h1>회원가입</h1>
{% else %}
    <h1>로그인</h1>
{% endif %}


<form action="" method="POST">
    {% csrf_token %}
    <!-- {{form}} -->
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary">
</form>

{% endblock %}

articles/templates/form.html
{% extends 'base.html' %}

{% block body %}

<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>

{% endblock %}

articles/templates/index.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}

{% for article in articles %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{article.title}}</h5>
            <p class="card-text">{{article.content}}</p>
            <p class="card-text">{{article.user}}</p>
        </div>

        {% if request.user.is_authenticated %}
        <div class="card-footer">
            <form action="{% url 'articles:comment_create' article_id=article.id %}" method="POST">
                {% csrf_token %}
                {% bootstrap_form comment_form %}
                <input type="submit">
            </form>
        </div>
        {% endif %}

        <div class="card-footer">
            {% for comment in article.comment_set.all %}
            <p>
                {{comment.user}} : {{comment.content}}
            </p>
            {% endfor %}
        </div>

    </div>
{% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'articles:index' %}">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                    <a class="nav-link" href="{% url 'articles:create' %}">Create</a>
                    <a class="nav-link disabled">{{user}}</a>
                {% else %}
                    <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                {% endif %}
            </div>
          </div>
        </div>
    </nav>

    <div class="container">
        {% block body %}
            
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>